#!/usr/bin/env bash

container_ids=$(docker ps -q)
if [[ $container_ids ]]; then
  docker rm -f $container_ids
fi

stopped_containers=$(docker ps -a | grep Exit | awk '{print $1}')
if [[ $stopped_containers ]]; then
  docker rm $stopped_containers
fi

interim_images=$(docker images | grep '<none>' | awk '{print $3}')
if [[ $interim_images ]]; then
  docker rmi $interim_images
fi

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes
