#!/usr/bin/env bash

release=trusty
docker_hostname=docker_host
docker_ip=$(getent hosts $docker_hostname | awk '{print $1}')

if [ -z "$docker_ip" ]; then
    >&2 echo "$0: Unable to determine ip for $docker_hostname.
Is it defined in /etc/hosts?"
    exit 1
fi

image_name=$release-$1
cid=$(docker images -q $image_name)
if [ -z "$cid" ]; then
    image_name=$1
    cid=$(docker images -q $image_name)
    if [ -z "$cid" ]; then
        >&2 echo "$0: $image_name: No such image"
        exit 1
    fi
fi

docker run -d -P -v /opt/dev:/opt/dev:rw -v /opt/mirrors:/opt/mirrors:rw \
    --add-host="igor:$docker_ip" --name $1 $image_name

# Give ssh some time to launch
sleep 0.1
dsh $1
